export enum Phase {
  IDLE = 'IDLE',
  REGISTER = 'REGISTER',
  MESH = 'MESH',
  DEPLOY = 'DEPLOY',
  STITCH = 'STITCH',
}

export enum NodeStatus {
  REGISTERED = 'REGISTERED',
  RANGED = 'RANGED',
  MESHED = 'MESHED',
  DEPLOYED = 'DEPLOYED',
  UPLOADED = 'UPLOADED',
  ERROR = 'ERROR',
}

export enum WsMessageType {
  PING = 'PING',
  PONG = 'PONG',
  PHASE_CHANGE = 'PHASE_CHANGE',
  NODE_REGISTERED = 'NODE_REGISTERED',
  NODE_DISCONNECTED = 'NODE_DISCONNECTED',
  RANGING_RESULT = 'RANGING_RESULT',
  RSSI_RESULT = 'RSSI_RESULT',
  MESH_UPDATE = 'MESH_UPDATE',
  CAPTURE_START = 'CAPTURE_START',
  UPLOAD_COMPLETE = 'UPLOAD_COMPLETE',
  STITCH_COMPLETE = 'STITCH_COMPLETE',
  DEPLOY_ORDER = 'DEPLOY_ORDER',
  KILL = 'KILL',
  KICK = 'KICK',
}
